export const MASTER_DIRECTIVE_KEYS = {
    LIMITE_RECEPCIONES_PARCIALES_OCM: "LIMITE_RECEPCIONES_PARCIALES_OCM",
} as const;

export const TOPE_GLOBAL_RECEPCIONES_OCM_DEFAULT = 3;
export const LIMITE_PROVEEDOR_RECEPCIONES_OCM_DEFAULT = 2;

export const MASTER_DIRECTIVE_DEFAULTS = {
    LIMITE_RECEPCIONES_PARCIALES_OCM: TOPE_GLOBAL_RECEPCIONES_OCM_DEFAULT,
} as const;
