export const MASTER_DIRECTIVE_KEYS = {
    LIMITE_RECEPCIONES_PARCIALES_OCM: "LIMITE_RECEPCIONES_PARCIALES_OCM",
    DISPENSACION_NO_BLOQUEA_INICIO_PRODUCCION: "DISPENSACION_NO_BLOQUEA_INICIO_PRODUCCION",
    ENABLE_MASTER_SUPERMASTER_DIRECTIVES_ACCESS: "ENABLE_MASTER_SUPERMASTER_DIRECTIVES_ACCESS",
    MPS_SEMANAL_DIAS_BLOQUEO_EDICION: "MPS_SEMANAL_DIAS_BLOQUEO_EDICION",
    AREA_OPERATIVA_NOISE_ENABLED: "AREA_OPERATIVA_NOISE_ENABLED",
    AREA_OPERATIVA_NOISE_INTERVAL_MINUTES: "AREA_OPERATIVA_NOISE_INTERVAL_MINUTES",
    AREA_OPERATIVA_NOISE_SAMPLE_SECONDS: "AREA_OPERATIVA_NOISE_SAMPLE_SECONDS",
} as const;

export const TOPE_GLOBAL_RECEPCIONES_OCM_DEFAULT = 3;
export const LIMITE_PROVEEDOR_RECEPCIONES_OCM_DEFAULT = 2;
export const DISPENSACION_NO_BLOQUEA_INICIO_PRODUCCION_DEFAULT = true;
export const ENABLE_MASTER_SUPERMASTER_DIRECTIVES_ACCESS_DEFAULT = true;
export const MPS_SEMANAL_DIAS_BLOQUEO_EDICION_DEFAULT = 2;
export const AREA_OPERATIVA_NOISE_ENABLED_DEFAULT = false;
export const AREA_OPERATIVA_NOISE_INTERVAL_MINUTES_DEFAULT = 15;
export const AREA_OPERATIVA_NOISE_SAMPLE_SECONDS_DEFAULT = 2;
export const AREA_OPERATIVA_NOISE_INTERVAL_MINUTES_MIN = 10;
export const AREA_OPERATIVA_NOISE_INTERVAL_MINUTES_MAX = 60;
export const AREA_OPERATIVA_NOISE_SAMPLE_SECONDS_MIN = 1;
export const AREA_OPERATIVA_NOISE_SAMPLE_SECONDS_MAX = 5;

export const MASTER_DIRECTIVE_DEFAULTS = {
    LIMITE_RECEPCIONES_PARCIALES_OCM: TOPE_GLOBAL_RECEPCIONES_OCM_DEFAULT,
    DISPENSACION_NO_BLOQUEA_INICIO_PRODUCCION: DISPENSACION_NO_BLOQUEA_INICIO_PRODUCCION_DEFAULT,
    ENABLE_MASTER_SUPERMASTER_DIRECTIVES_ACCESS: ENABLE_MASTER_SUPERMASTER_DIRECTIVES_ACCESS_DEFAULT,
    MPS_SEMANAL_DIAS_BLOQUEO_EDICION: MPS_SEMANAL_DIAS_BLOQUEO_EDICION_DEFAULT,
    AREA_OPERATIVA_NOISE_ENABLED: AREA_OPERATIVA_NOISE_ENABLED_DEFAULT,
    AREA_OPERATIVA_NOISE_INTERVAL_MINUTES: AREA_OPERATIVA_NOISE_INTERVAL_MINUTES_DEFAULT,
    AREA_OPERATIVA_NOISE_SAMPLE_SECONDS: AREA_OPERATIVA_NOISE_SAMPLE_SECONDS_DEFAULT,
} as const;
